# Generated by Django 4.2.24 on 2025-09-09 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('qna', '문의하기'), ('notice', '공지사항')], default='qna', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='voter_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pre', '택배 사전 접수'), ('find', '택배 찾기'), ('qna', '문의하기'), ('notice', '공지사항')], default='pre', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('send_name', models.CharField(max_length=50)),
                ('send_phone', models.CharField(max_length=20)),
                ('send_addr_zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('send_addr_road', models.CharField(blank=True, max_length=200, null=True)),
                ('send_addr_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('rec_name', models.CharField(max_length=50)),
                ('rec_phone', models.CharField(max_length=20)),
                ('rec_addr_zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('rec_addr_road', models.CharField(blank=True, max_length=200, null=True)),
                ('rec_addr_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('product_type', models.CharField(max_length=100)),
                ('package_type', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_pre_question', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='voter_pre_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Find_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('send_name', models.CharField(max_length=50)),
                ('send_phone', models.CharField(max_length=20)),
                ('send_addr', models.CharField(blank=True, max_length=200, null=True)),
                ('product_type', models.CharField(max_length=100)),
                ('package_type', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_find_question', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='voter_find_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_answer', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
                ('voter', models.ManyToManyField(related_name='voter_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
