# Generated by Django 4.2.24 on 2025-09-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='find_question',
            old_name='send_addr',
            new_name='send_addr_detail',
        ),
        migrations.AddField(
            model_name='find_question',
            name='send_addr_road',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='find_question',
            name='send_addr_zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pre_question',
            name='pay_method',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
